export let defaultDataCardAll = {
  dsh1:[
    {
      URUTAN:0,
      SEQ : "HEADER",
      GRP : "ALL_PRJ",
      NILAI : 2201,
      PERSEN: 2200,
      AREA1 : 0,
      AREA2 : 0,
      AREA3 : 0,
      AREA4 : 0,
    },
    {
      URUTAN:1,
      SEQ : "HEADER",
      GRP : "NOT_RELEASE",
      NILAI : 0,
      PERSEN: 0,
      AREA1 : 0,
      AREA2 : 0,
      AREA3 : 0,
      AREA4 : 0,
    },
    {
      URUTAN:2,
      SEQ : "HEADER",
      GRP : "PRJ_ON_PIPE",
      NILAI : 0,
      PERSEN: 0,
      AREA1 : 0,
      AREA2 : 0,
      AREA3 : 0,
      AREA4 : 0,
    },
    {
      URUTAN:3,
      SEQ : "HEADER",
      GRP : "RFI",
      NILAI : 0,
      PERSEN: 0,
      AREA1 : 0,
      AREA2 : 0,
      AREA3 : 0,
      AREA4 : 0,
    },
    {
      URUTAN:4,
      SEQ : "HEADER",
      GRP : "ARFI",
      NILAI : 0,
      PERSEN: 0,
      AREA1 : 0,
      AREA2 : 0,
      AREA3 : 0,
      AREA4 : 0,
    },
    //-B2S-NOT_RELEASE
    {
      URUTAN:0,
      SEQ : "B2S",
      GRP : "NOT_RELEASE",
      NILAI : 0,
      PERSEN: 0,
      AREA1 : 0,
      AREA2 : 0,
      AREA3 : 0,
      AREA4 : 0,
    },
    {
      URUTAN:1,
      SEQ : "B2S",
      GRP : "NOT_RELEASE",
      NILAI : 0,
      PERSEN: 0,
      AREA1 : 0,
      AREA2 : 0,
      AREA3 : 0,
      AREA4 : 0,
    },
    {
      URUTAN:2,
      SEQ : "B2S",
      GRP : "NOT_RELEASE",
      NILAI : 0,
      PERSEN: 0,
      AREA1 : 0,
      AREA2 : 0,
      AREA3 : 0,
      AREA4 : 0,
    },
    {
      URUTAN:3,
      SEQ : "B2S",
      GRP : "NOT_RELEASE",
      NILAI : 0,
      PERSEN: 0,
      AREA1 : 0,
      AREA2 : 0,
      AREA3 : 0,
      AREA4 : 0,
    },
    //-B2S-PRJ_ON_PIPE
    {
      URUTAN:0,
      SEQ : "B2S",
      GRP : "PRJ_ON_PIPE",
      NILAI : 0,
      PERSEN: 0,
      AREA1 : 0,
      AREA2 : 0,
      AREA3 : 0,
      AREA4 : 0,
    },
    {
      URUTAN:1,
      SEQ : "B2S",
      GRP : "PRJ_ON_PIPE",
      NILAI : 0,
      PERSEN: 0,
      AREA1 : 0,
      AREA2 : 0,
      AREA3 : 0,
      AREA4 : 0,
    },
    {
      URUTAN:2,
      SEQ : "B2S",
      GRP : "PRJ_ON_PIPE",
      NILAI : 0,
      PERSEN: 0,
      AREA1 : 0,
      AREA2 : 0,
      AREA3 : 0,
      AREA4 : 0,
    },
    {
      URUTAN:3,
      SEQ : "B2S",
      GRP : "PRJ_ON_PIPE",
      NILAI : 0,
      PERSEN: 0,
      AREA1 : 0,
      AREA2 : 0,
      AREA3 : 0,
      AREA4 : 0,
    },
    //-B2S-RFI
    {
      URUTAN:0,
      SEQ : "B2S",
      GRP : "RFI",
      NILAI : 0,
      PERSEN: 0,
      AREA1 : 0,
      AREA2 : 0,
      AREA3 : 0,
      AREA4 : 0,
    },
    {
      URUTAN:1,
      SEQ : "B2S",
      GRP : "RFI",
      NILAI : 0,
      PERSEN: 0,
      AREA1 : 0,
      AREA2 : 0,
      AREA3 : 0,
      AREA4 : 0,
    },
    {
      URUTAN:2,
      SEQ : "B2S",
      GRP : "RFI",
      NILAI : 0,
      PERSEN: 0,
      AREA1 : 0,
      AREA2 : 0,
      AREA3 : 0,
      AREA4 : 0,
    },
    {
      URUTAN:3,
      SEQ : "B2S",
      GRP : "RFI",
      NILAI : 0,
      PERSEN: 0,
      AREA1 : 0,
      AREA2 : 0,
      AREA3 : 0,
      AREA4 : 0,
    },
    //-B2S-ARFI
    {
      URUTAN:0,
      SEQ : "B2S",
      GRP : "ARFI",
      NILAI : 0,
      PERSEN: 0,
      AREA1 : 0,
      AREA2 : 0,
      AREA3 : 0,
      AREA4 : 0,
    },
    {
      URUTAN:1,
      SEQ : "B2S",
      GRP : "ARFI",
      NILAI : 0,
      PERSEN: 0,
      AREA1 : 0,
      AREA2 : 0,
      AREA3 : 0,
      AREA4 : 0,
    },
    {
      URUTAN:2,
      SEQ : "B2S",
      GRP : "ARFI",
      NILAI : 0,
      PERSEN: 0,
      AREA1 : 0,
      AREA2 : 0,
      AREA3 : 0,
      AREA4 : 0,
    },
    {
      URUTAN:3,
      SEQ : "B2S",
      GRP : "ARFI",
      NILAI : 0,
      PERSEN: 0,
      AREA1 : 0,
      AREA2 : 0,
      AREA3 : 0,
      AREA4 : 0,
    },
  ]
};
