export let GET_STRING_TABLE = [
  {
    ID:1,
    NAME:"CREATE TESTING TEBEL",
    TABEL:"CREATE TABLE IF NOT EXISTS piter (UNIQ_ID TEXT NOT NULL,NAME TEXT,SUMMARY TEXT,COMPANY TEXT)",
    UNIQUE:"CREATE UNIQUE INDEX IF NOT EXISTS idx_UNIQ_ID ON piter (UNIQ_ID)",
  },
  {
    ID:2,
    NAME:"CREATE APPSETTING TEBEL",
    TABEL:"CREATE TABLE IF NOT EXISTS APPSETTING (SORT TEXT,GRP TEXT, BULAN TEXT,TAHUN TEXT,NAME TEXT,NILAI TEXT,STT_ACTIVE REAL)",
    UNIQUE:"CREATE UNIQUE INDEX IF NOT EXISTS APPSETTING_UNIQ_ID ON APPSETTING (SORT,GRP,NAME,NILAI,BULAN,TAHUN)",
  },
  {
    ID:3,
    NAME:"CREATE ALL PROJECT TEBEL",
    TABEL:"CREATE TABLE IF NOT EXISTS ALL_PRJ (URUTAN TEXT, SEQ TEXT, GRP TEXT, BULAN TEXT,TAHUN TEXT, NILAI REAL,PERSEN REAL, AREA1 REAL,AREA2 REAL,AREA3 REAL,AREA4 REAL)",
    UNIQUE:"CREATE UNIQUE INDEX IF NOT EXISTS ALL_PRJ_UNIQ_ID ON ALL_PRJ (URUTAN,SEQ,GRP,BULAN,TAHUN)",
  },
  {
    ID:4,
    NAME:"CREATE B2S PROJECT TEBEL",
    TABEL:"CREATE TABLE IF NOT EXISTS B2S_PRJ (URUTAN TEXT, SEQ TEXT, GRP TEXT,BULAN TEXT,TAHUN TEXT,NILAI REAL,PERSEN REAL,AREA1 REAL,AREA2 REAL,AREA3 REAL,AREA4 REAL,SIS REAL,SITAC1 REAL,SITAC2 REAL,CME REAL,RFC REAL,RFI REAL,ARFI_NILAI2 REAL)",
    UNIQUE:"CREATE UNIQUE INDEX IF NOT EXISTS B2S_PRJ_UNIQ_ID ON B2S_PRJ (URUTAN,SEQ,GRP,BULAN,TAHUN)",
  },
  {
    ID:5,
    NAME:"CREATE CORE ROJECT TEBEL",
    TABEL:"CREATE TABLE IF NOT EXISTS CORE_PRJ (URUTAN TEXT, SEQ TEXT, GRP TEXT, BULAN TEXT,TAHUN TEXT, NILAI REAL,PERSEN REAL,AREA1 REAL,AREA2 REAL,AREA3 REAL,AREA4 REAL,SurveySITAC REAL,CME REAL,RFI REAL,BAUT REAL,ARFI_NILAI2 REAL)",
    UNIQUE:"CREATE UNIQUE INDEX IF NOT EXISTS CORE_PRJ_UNIQ_ID ON CORE_PRJ (URUTAN,SEQ,GRP,BULAN,TAHUN)",
  },
  {
    ID:6,
    NAME:"CREATE MICROCELL PROJECT TEBEL",
    TABEL:"CREATE TABLE IF NOT EXISTS MCP_PRJ (URUTAN TEXT, SEQ TEXT, GRP TEXT, BULAN TEXT,TAHUN TEXT, NILAI REAL,PERSEN REAL,AREA1 REAL,AREA2 REAL,AREA3 REAL,AREA4 REAL,SIS REAL,SITAC1 REAL,SITAC2 REAL,CME REAL,RFC REAL,FO REAL,RFI REAL,ARFI_NILAI2)",
    UNIQUE:"CREATE UNIQUE INDEX IF NOT EXISTS MCP_PRJ_UNIQ_ID ON MCP_PRJ (URUTAN,SEQ,GRP,BULAN,TAHUN)",
  },
  {
    ID:7,
    NAME:"CREATE SPECIAL PROJECT TEBEL",
    TABEL:"CREATE TABLE IF NOT EXISTS SP_PRJ (URUTAN TEXT, SEQ TEXT, GRP TEXT, BULAN TEXT,TAHUN TEXT,NILAI REAL,PERSEN REAL,AREA1 REAL,AREA2 REAL,AREA3 REAL,AREA4 REAL,BAST REAL,ARFI_NILAI2 REAL)",
    UNIQUE:"CREATE UNIQUE INDEX IF NOT EXISTS SP_PRJ_UNIQ_ID ON SP_PRJ (URUTAN,SEQ,GRP,BULAN,TAHUN)",
  },
  {
    ID:8,
    NAME:"CREATE CHART TEBEL DATA",
    TABEL:"CREATE TABLE IF NOT EXISTS TBL_CHART(ID_CHART TEXT, BULAN TEXT,TAHUN TEXT, NM_CHART TEXT, TITLE TEXT,KTG TEXT,TARGET_RFI TEXT, ACTUAL_RFI TEXT,TARGET,ACTUAL TEXT)",
    UNIQUE:"CREATE UNIQUE INDEX IF NOT EXISTS TBL_CHART_UNIQ_ID ON TBL_CHART (ID_CHART,BULAN,TAHUN)",
  },
  {
    ID:9,
    NAME:"CREATE MAP ALL PROJECT",
    TABEL:"CREATE TABLE IF NOT EXISTS TBL_PETA(GRP TEXT,PROJECT_ID TEXT,BULAN TEXT,TAHUN TEXT,AREA TEXT,LAT REAL,LONG REAL,RADIUS REAL,SITE_NM text,TENAN_NM text,REGIONAL text,SOW text,STATUS text)",
    UNIQUE:"CREATE UNIQUE INDEX IF NOT EXISTS TBL_PETA_UNIQ_ID ON TBL_PETA (GRP,PROJECT_ID,BULAN,TAHUN,AREA)",
    // GROUP [RFI,RELEASE, NOT-RELEASE]
    // Filter [BULAN/TAHUN]
    // Filter Area [1,2,3,4]
    //site_name,nama_tenant,regional,sow,status
    // SITE_NM text, TENAN_NM text, REGIONAL text, SOW text, STATUS text
  },
  {
    ID:10,
    NAME:"CREATE MAP B2S",
    TABEL:"CREATE TABLE IF NOT EXISTS TBL_PETA_B2S(GRP TEXT,PROJECT_ID TEXT,BULAN TEXT,TAHUN TEXT,AREA TEXT,LAT REAL,LONG REAL,RADIUS REAL,SITE_NM text,TENAN_NM text,REGIONAL text,SOW text,STATUS text)",
    UNIQUE:"CREATE UNIQUE INDEX IF NOT EXISTS TBL_PETA_B2S_UNIQ_ID ON TBL_PETA_B2S (GRP,PROJECT_ID,BULAN,TAHUN,AREA)",
  },
  {
    ID:11,
    NAME:"CREATE MAP CORE ROJECT",
    TABEL:"CREATE TABLE IF NOT EXISTS TBL_PETA_CORE(GRP TEXT,PROJECT_ID TEXT,BULAN TEXT,TAHUN TEXT,AREA TEXT,LAT REAL,LONG REAL,RADIUS REAL,SITE_NM text,TENAN_NM text,REGIONAL text,SOW text,STATUS text)",
    UNIQUE:"CREATE UNIQUE INDEX IF NOT EXISTS TBL_PETA_CORE_UNIQ_ID ON TBL_PETA_CORE (GRP,PROJECT_ID,BULAN,TAHUN,AREA)",
  },
  {
    ID:12,
    NAME:"CREATE MAP MICROCELL ROJECT",
    TABEL:"CREATE TABLE IF NOT EXISTS TBL_PETA_MCP(GRP TEXT,PROJECT_ID TEXT,BULAN TEXT,TAHUN TEXT,AREA TEXT,LAT REAL,LONG REAL,RADIUS REAL,SITE_NM text,TENAN_NM text,REGIONAL text,SOW text,STATUS text)",
    UNIQUE:"CREATE UNIQUE INDEX IF NOT EXISTS TBL_PETA_MCP_UNIQ_ID ON TBL_PETA_MCP (GRP,PROJECT_ID,BULAN,TAHUN,AREA)",
  },
  {
    ID:13,
    NAME:"CREATE MAP SPECIAL PROJECT",
    TABEL:"CREATE TABLE IF NOT EXISTS TBL_PETA_SP(GRP TEXT,PROJECT_ID TEXT,BULAN TEXT,TAHUN TEXT,AREA TEXT,LAT REAL,LONG REAL,RADIUS REAL,SITE_NM text,TENAN_NM text,REGIONAL text,SOW text,STATUS text)",
    UNIQUE:"CREATE UNIQUE INDEX IF NOT EXISTS TBL_PETA_SP_UNIQ_ID ON TBL_PETA_SP (GRP,PROJECT_ID,BULAN,TAHUN,AREA)",
  },
  {
    ID:14,
    NAME:"CREATE USER",
    TABEL:"CREATE TABLE IF NOT EXISTS TBL_USER(USER_ID TEXT,USERNAME TEXT,PASSWORD TEXT,REAL_NAME TEXT,EMAIL TEXT,USER_GROUP TEXT)",
    UNIQUE:"CREATE UNIQUE INDEX IF NOT EXISTS TBL_PETA_SP_UNIQ_ID ON TBL_PETA_SP (USER_ID,USERNAME)",
  }
];
