export let GET_STRING_TABLE = [
  {
    ID:1,
    NAME:"CREATE TESTING TEBEL",
    TABEL:"CREATE TABLE IF NOT EXISTS piter (UNIQ_ID TEXT NOT NULL,NAME TEXT,SUMMARY TEXT,COMPANY TEXT)",
    UNIQUE:"CREATE UNIQUE INDEX IF NOT EXISTS idx_UNIQ_ID ON piter (UNIQ_ID)",
  },
  {
    ID:2,
    NAME:"CREATE APPSETTING TEBEL",
    TABEL:"CREATE TABLE IF NOT EXISTS APPSETTING (SORT TEXT,GRP TEXT,NAME TEXT ,NILAI TEXT,STT_ACTIVE REAL)",
    UNIQUE:"CREATE UNIQUE INDEX IF NOT EXISTS APPSETTING_UNIQ_ID ON APPSETTING (SORT,GRP,NAME,NILAI)",
  },
  {
    ID:3,
    NAME:"CREATE ALLPROJECT TEBEL",
    TABEL:"CREATE TABLE IF NOT EXISTS ALL_PRJ (URUTAN TEXT, SEQ TEXT, GRP TEXT, NILAI REAL, PERSEN REAL, AREA1 REAL,AREA2 REAL,AREA3 REAL,AREA4 REAL)",
    UNIQUE:"CREATE UNIQUE INDEX IF NOT EXISTS ALL_PRJ_UNIQ_ID ON ALL_PRJ (URUTAN,SEQ,GRP)",
  },
];
