export let GET_STRING_TABLE = [
  {
    ID:1,
    NAME:"CREATE TESTING TEBEL",
    TABEL:"CREATE TABLE IF NOT EXISTS piter (UNIQ_ID TEXT NOT NULL,NAME TEXT,SUMMARY TEXT,COMPANY TEXT)",
    UNIQUE:"CREATE UNIQUE INDEX IF NOT EXISTS idx_UNIQ_ID ON piter (UNIQ_ID)",
  },
  {
    ID:2,
    NAME:"CREATE APPSETTING TEBEL",
    TABEL:"CREATE TABLE IF NOT EXISTS APPSETTING (SORT TEXT,GRP TEXT,NAME TEXT ,NILAI TEXT,STT_ACTIVE REAL)",
    UNIQUE:"CREATE UNIQUE INDEX IF NOT EXISTS APPSETTING_UNIQ_ID ON APPSETTING (SORT,GRP,NAME,NILAI)",
  },
  {
    ID:3,
    NAME:"CREATE ALL PROJECT TEBEL",
    TABEL:"CREATE TABLE IF NOT EXISTS ALL_PRJ (URUTAN TEXT, SEQ TEXT, GRP TEXT, NILAI REAL, PERSEN REAL, AREA1 REAL,AREA2 REAL,AREA3 REAL,AREA4 REAL)",
    UNIQUE:"CREATE UNIQUE INDEX IF NOT EXISTS ALL_PRJ_UNIQ_ID ON ALL_PRJ (URUTAN,SEQ,GRP)",
  },
  {
    ID:4,
    NAME:"CREATE B2S PROJECT TEBEL",
    TABEL:"CREATE TABLE IF NOT EXISTS B2S_PRJ (URUTAN TEXT, SEQ TEXT, GRP TEXT, NILAI REAL, PERSEN REAL, AREA1 REAL,AREA2 REAL,AREA3 REAL,AREA4 REAL,SIS REAL,SITAC1 REAL,SITAC2 REAL,CME REAL,RFC REAL,RFI REAL)",
    UNIQUE:"CREATE UNIQUE INDEX IF NOT EXISTS B2S_PRJ_UNIQ_ID ON B2S_PRJ (URUTAN,SEQ,GRP)",
  },
  {
    ID:5,
    NAME:"CREATE CORE ROJECT TEBEL",
    TABEL:"CREATE TABLE IF NOT EXISTS CORE_PRJ (URUTAN TEXT, SEQ TEXT, GRP TEXT, NILAI REAL, PERSEN REAL, AREA1 REAL,AREA2 REAL,AREA3 REAL,AREA4 REAL,SurveySITAC REAL,CME REAL,RFI REAL,BAUT REAL)",
    UNIQUE:"CREATE UNIQUE INDEX IF NOT EXISTS CORE_PRJ_UNIQ_ID ON CORE_PRJ (URUTAN,SEQ,GRP)",
  },
  {
    ID:6,
    NAME:"CREATE MICROCELL PROJECT TEBEL",
    TABEL:"CREATE TABLE IF NOT EXISTS MCP_PRJ (URUTAN TEXT, SEQ TEXT, GRP TEXT, NILAI REAL, PERSEN REAL, AREA1 REAL,AREA2 REAL,AREA3 REAL,AREA4 REAL,SIS REAL,SITAC1 REAL,SITAC2 REAL,CME REAL,RFC REAL,FO REAL,RFI REAL)",
    UNIQUE:"CREATE UNIQUE INDEX IF NOT EXISTS MCP_PRJ_UNIQ_ID ON MCP_PRJ (URUTAN,SEQ,GRP)",
  },
  {
    ID:7,
    NAME:"CREATE SPECIAL PROJECT TEBEL",
    TABEL:"CREATE TABLE IF NOT EXISTS SP_PRJ (URUTAN TEXT, SEQ TEXT, GRP TEXT, NILAI REAL, PERSEN REAL, AREA1 REAL,AREA2 REAL,AREA3 REAL,AREA4 REAL,BAST REAL)",
    UNIQUE:"CREATE UNIQUE INDEX IF NOT EXISTS SP_PRJ_UNIQ_ID ON SP_PRJ (URUTAN,SEQ,GRP)",
  },
];
